### ISSUE TITLE
Faulty Autocomplete For References with Multiple Words

### ISSUE THREAD

**Issue by SundermannC** [Universal-Variability-Language/uvl-lsp#71] opened 2023-08-22 11:01 UTC
When typing in multiple (2+) words that are part of a reference with multiple words (i.e., spaces), the autocomplete replaces only the last added word.

For instance:
![image](https://github.com/Universal-Variability-Language/uvl-lsp/assets/24757266/ba546da7-5c02-48fe-96af-305966babb2f)

results in 
![image](https://github.com/Universal-Variability-Language/uvl-lsp/assets/24757266/c69857ba-4ea7-4a2b-99fe-514203f1ec7e)

**Comment by TobnacTobi** [comment] 2023-09-15 06:07
I've done a lot of debugging and I'm pretty sure that a solution to this would need a deep restructure of the Tree, Parser and internal representation. The problem is, that words separated by a space character are immediately interpreted as a _"typed_feature"_ (as you can see by the green "Name" in your example).  
I've managed to add some ugly code [here](https://github.com/Universal-Variability-Language/uvl-lsp/blob/master/uvls/src/core/parse.rs#L111) to make this work with two separate words, but it's not a proper solution.   
It already fails with 3 or more words in a row, since this is parsed/interpreted as separate typed_features etc.


It works fine if you start with quotes and type any part of the feature_name inbetween.  

Question: Should i add the solution for two words (typed_feature) or is it better to leave the code as it is?  
(This feature already fails if there is something like a bool expression before it)

**Comment by TobiUUlm** [comment] 2023-10-13 07:04
In a meeting we decided that this feature is not worth the restructuring and that we can not think of another language that handles this kind of problem.  
Closing.

**Closed by TobiUUlm** 2023-10-13 07:04 UTC
Labels: bug, Autocompletion
