### ISSUE TITLE
Error with feature names containing dashes

### ISSUE THREAD

**Issue by jagalindo** [Universal-Variability-Language/uvl-lsp#14] opened 2023-04-14 16:42 UTC
Currently we observe that when having a dash (-) in an identifier of a UVL file, it mark it as erroneous.

**Comment by lothran** [comment] 2023-04-16 05:44
The grammar roughly follows https://github.com/Universal-Variability-Language/uvl-parser2.0/blob/main/src/main/antlr4/de/vill/UVL.g4, there names are not allowed to contain dashes (Which makes sense because we want a deterministic arithmetic minus). You could rename the files using a namespace or replace '-' with '_'.

**Comment by SundermannC** [comment] 2023-04-19 19:25
Thanks a lot for the report, @jagalindo.
As addition to the comments of @lothran, you can still use a dash in feature names, but you need to put the feature name into parentheses (e.g., "Feature-Name"). Generally, the rules for features names are only strict without parentheses to prevent ambiguities. This applies to both this LSP and the [UVL Parser 2.0](https://github.com/Universal-Variability-Language/uvl-parser2.0/blob/main/src/main/antlr4/de/vill/UVL.g4). See also the following excerpt from the linked g4 grammar of the UVL Parser 2.0.

```
ID_NOT_STRICT: '"'~[\r\n".]+'"';
ID_STRICT: [a-zA-Z]([a-zA-Z0-9_] | '#' | '§' | '%' | '?' | '\\' | '\'' | 'ä' | 'ü' | 'ö' | 'ß' | ';')*;
```

**Comment by SundermannC** [comment] 2023-05-16 11:16
While this is (currently) intended behavior, it may still be useful to automatically fix violating feature names (i.e., put them in "") . Resolving issues with feature names by hand is tedious and error prone.

**Closed** 2023-07-11 15:17 UTC
Labels: Language
